# Copyright (c) 2024 - now Shuaiwen Cui
# Built upon MkDocs & Material for MkDocs

# Project information
site_name: TinyAuton
site_url: https://localhost:8000/ # build and run on server, to visit it, type in the server's IP address and port number like this: xxx.xxx.xxx.xxx:8000
site_author: Shuaiwen Cui
site_description: >-
  
# Repository
repo_name: Shuaiwen-Cui/TinyAuton
repo_url: https://github.com/Shuaiwen-Cui/TinyAuton.git

# Copyright
copyright: Copyright &copy; 2025 ~ now | 🚀 Shuaiwen Cui (Shaun)

# Configuration
theme:
  name: material
  language: en
  logo: static/images/logo.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand # expand the side navigation bar by default
    - navigation.footer
    - navigation.indexes # documents can be directly attached to sections, which is particularly useful for providing overview pages
    # - navigation.instant
    - navigation.instant.prefetch # for large file
    - navigation.instant.progress # loading progress bar
    - navigation.path # breadcrumb path on top of page
    # - navigation.prune # only build the visible part of the navigation tree
    # - navigation.sections # navigation - top level will render as sections
    - navigation.tabs
    - navigation.tabs.sticky # tabs stick to the top of the page
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate # toc is merged into the left navigation bar
  palette:
    - media: "(prefers-color-scheme)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: static/images/logo.png
  icon:
    logo: logo
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      default-tag: fontawesome/solid/tag
      hardware-tag: fontawesome/solid/microchip
      software-tag: fontawesome/solid/laptop-code

# Plugins
plugins:
  - tags
  - blog
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
  # - social
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  # - privacy
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          # site_name: Infinity
        - locale: zh
          name: 简体中文
          build: true
          nav_translations: # note that all titles and subtitles in the navigation bar that need to be translated can be put here, but with no indentation
            ABOUT: 关于
            ARCHITECTURE: 架构
            PREREQUISITE: 前置条件
            TOOLBOX: 工具箱
            TIME: 时间
            MATH: 数学运算
            HEADER-FILE: 头文件
            CONSTANTS: 常量
            ERROR-TYPE: 错误类型
            CONFIGURATION: 配置
            TINYMATH: TinyMath库头文件
            ESP-DSP: ESP数字信号处理
            VECTOR: 向量操作
            API: 应用程序接口
            TEST: 测试
            MATRIX: 矩阵操作
            TINY_MAT-API: TINY_MAT-接口
            TINY_MAT-CODE: TINY_MAT-代码
            TINY_MAT-TEST: TINY_MAT-测试
            TINY_MATRIX-API: TINY_MATRIX-接口
            TINY_MATRIX-CODE: TINY_MATRIX-代码
            TINY_MATRIX-TEST: TINY_MATRIX-测试
            USAGE: 使用方法
            EXAMPLES: 示例
            DSP: 数字信号处理
            SUPPORT: 支持功能
            SIGNAL: 信号
            CONVOLUTION: 卷积
            CORRELATION: 互相关
            RESAMPLING: 重采样
            TRANSFORM: 变换
            FFT: 快速傅里叶变换
            DWT: 离散小波变换
            ICA: 独立成分分析
            FILTER: 滤波器
            FIR: 有限脉冲响应
            IIR: 无限脉冲响应
            AI: 人工智能
            NOTES: 说明
            CODE: 代码
            LOG: 日志
            CORE: 核心
            LAYERS: 网络层
            MODELS: 模型
            QUANT: 量化
            TRAIN: 训练
            TENSOR: 张量
            ACTIVATION: 激活函数
            LOSS: 损失函数
            OPTIMIZER: 优化器
            BASE: 基础层
            DENSE: 全连接
            CONV: 卷积
            POOL: 池化
            NORM: 归一化
            ATTENTION: 注意力
            SEQUENTIAL: 序列容器
            MLP: 多层感知机
            CNN: 卷积神经网络
            INT: 整型量化
            FP8: FP8量化
            DATASET: 数据集
            TRAINER: 训练器
            TINYAI: TinyAI库头文件
            TINYAI-CONFIG: TinyAI配置

# # Hooks
# hooks:
#   - material/overrides/hooks/shortcodes.py
#   - material/overrides/hooks/translations.py 

# Additional configuration 
extra:
  generator: false
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    # property: GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  # alternate:
  #   - name: English
  #     link: /en/ 
  #     lang: en
  #   - name: Chinese
  #     link: /zh/
  #     lang: zh
  social:
    - icon: fontawesome/solid/house
      link: http://www.cuishuaiwen.com/
    - icon: fontawesome/brands/github
      link: https://github.com/Shuaiwen-Cui
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shaun-shuaiwen-cui/
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Shuaiwen-Cui
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0003-4447-6687
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ShuaiwenC
  tags:
    Default: default-tag
    Hardware: hardware-tag
    Software: software-tag
  # consent:
  #   title: Cookie consent
  #   description: >- 
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.

# Extra Configuration 
extra_javascript:
  # - https://giscus.app/client.js
  # - javascripts/katex.js 
  # - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  # - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - javascripts/embed-pdf.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page Navigation Tree
nav:
  - ABOUT: 
      "index.md"
  - ARCHITECTURE:
      - "ARCHITECTURE/architecture.md"
  - PREREQUISITE:
      - "PREREQUISITE/prerequisite.md"
  - TOOLBOX:
      - TOOLBOX: "TOOLBOX/toolbox.md"
      - TIME: 
          - NOTES: "TOOLBOX/TIME/notes.md"
          - CODE: "TOOLBOX/TIME/code.md"
          - LOG: "TOOLBOX/TIME/log.md"
  - MATH:
      - "MATH/math.md"
      # - ESP-DSP: 
      #     - ESP-DSP: "MATH/ESP-DSP/esp-dsp.md"
      #     - EXAMPLES: "MATH/ESP-DSP/examples.md"
      - USAGE: "MATH/USAGE/usage.md"
      - HEADER-FILE:
          - CONSTANTS: "MATH/HEADER-FILE/tiny_constants.md"
          - ERROR-TYPE: "MATH/HEADER-FILE/tiny_error_type.md"
          - CONFIGURATION: "MATH/HEADER-FILE/tiny_math_config.md"
          - TINYMATH: "MATH/HEADER-FILE/tiny_math.md"
      - VECTOR: 
          - API: "MATH/VECTOR/api.md"
          - CODE: "MATH/VECTOR/code.md"
          - TEST: "MATH/VECTOR/test.md"
      - MATRIX:
          - TINY_MAT-API: "MATH/MATRIX/tiny-mat-api.md"
          - TINY_MAT-CODE: "MATH/MATRIX/tiny-mat-code.md"
          - TINY_MAT-TEST: "MATH/MATRIX/tiny-mat-test.md"
          - TINY_MATRIX-API: "MATH/MATRIX/tiny-matrix-api.md"
          - TINY_MATRIX-CODE: "MATH/MATRIX/tiny-matrix-code.md"
          - TINY_MATRIX-TEST: "MATH/MATRIX/tiny-matrix-test.md"
  - DSP:
      - "DSP/dsp.md"
      - USAGE: "DSP/USAGE/usage.md"
      - HEADER-FILE:
          - CONFIGURATION: "DSP/HEADER-FILE/tiny_dsp_config.md"
          - TINYDSP: "DSP/HEADER-FILE/tiny_dsp.md"
      - SUPPORT:
          - NOTES: "DSP/SUPPORT/notes.md"
          - CODE: "DSP/SUPPORT/code.md"
          - TEST: "DSP/SUPPORT/test.md"
      - SIGNAL:
          - CONVOLUTION: 
             - NOTES: "DSP/SIGNAL/CONVOLUTION/notes.md"
             - CODE: "DSP/SIGNAL/CONVOLUTION/code.md"
             - TEST: "DSP/SIGNAL/CONVOLUTION/test.md"
          - CORRELATION: 
             - NOTES: "DSP/SIGNAL/CORRELATION/notes.md"
             - CODE: "DSP/SIGNAL/CORRELATION/code.md"
             - TEST: "DSP/SIGNAL/CORRELATION/test.md"
          - RESAMPLING:
             - NOTES: "DSP/SIGNAL/RESAMPLE/notes.md"
             - CODE: "DSP/SIGNAL/RESAMPLE/code.md"
             - TEST: "DSP/SIGNAL/RESAMPLE/test.md"
      - FILTER:
          - FIR:
              - NOTES: "DSP/FILTER/FIR/notes.md"
              - CODE: "DSP/FILTER/FIR/code.md"
              - TEST: "DSP/FILTER/FIR/test.md"
          - IIR:
              - NOTES: "DSP/FILTER/IIR/notes.md"
              - CODE: "DSP/FILTER/IIR/code.md"
              - TEST: "DSP/FILTER/IIR/test.md"
      - TRANSFORM:
          - FFT:
              - NOTES: "DSP/TRANSFORM/FFT/notes.md"
              - CODE: "DSP/TRANSFORM/FFT/code.md"
              - TEST: "DSP/TRANSFORM/FFT/test.md"
          - DWT:
              - NOTES: "DSP/TRANSFORM/DWT/notes.md"
              - CODE: "DSP/TRANSFORM/DWT/code.md"
              - TEST: "DSP/TRANSFORM/DWT/test.md"
          - ICA:
              - NOTES: "DSP/TRANSFORM/ICA/notes.md"
              - CODE: "DSP/TRANSFORM/ICA/code.md"
              - TEST: "DSP/TRANSFORM/ICA/test.md"
  - AI:
      - "AI/ai.md"
      - USAGE: "AI/USAGE/usage.md"
      - HEADER-FILE:
          - TINYAI-CONFIG: "AI/HEADER-FILE/tiny_ai_config.md"
          - TINYAI: "AI/HEADER-FILE/tiny_ai.md"
      - CORE:
          - TENSOR:
              - NOTES: "AI/CORE/TENSOR/notes.md"
              - CODE: "AI/CORE/TENSOR/code.md"
          - ACTIVATION:
              - NOTES: "AI/CORE/ACTIVATION/notes.md"
              - CODE: "AI/CORE/ACTIVATION/code.md"
          - LOSS:
              - NOTES: "AI/CORE/LOSS/notes.md"
              - CODE: "AI/CORE/LOSS/code.md"
          - OPTIMIZER:
              - NOTES: "AI/CORE/OPTIMIZER/notes.md"
              - CODE: "AI/CORE/OPTIMIZER/code.md"
      - LAYERS:
          - BASE:
              - NOTES: "AI/LAYERS/BASE/notes.md"
              - CODE: "AI/LAYERS/BASE/code.md"
          - DENSE:
              - NOTES: "AI/LAYERS/DENSE/notes.md"
              - CODE: "AI/LAYERS/DENSE/code.md"
          - CONV:
              - NOTES: "AI/LAYERS/CONV/notes.md"
              - CODE: "AI/LAYERS/CONV/code.md"
          - POOL:
              - NOTES: "AI/LAYERS/POOL/notes.md"
              - CODE: "AI/LAYERS/POOL/code.md"
          - NORM:
              - NOTES: "AI/LAYERS/NORM/notes.md"
              - CODE: "AI/LAYERS/NORM/code.md"
          - ATTENTION:
              - NOTES: "AI/LAYERS/ATTENTION/notes.md"
              - CODE: "AI/LAYERS/ATTENTION/code.md"
      - MODELS:
          - SEQUENTIAL:
              - NOTES: "AI/MODELS/SEQUENTIAL/notes.md"
              - CODE: "AI/MODELS/SEQUENTIAL/code.md"
          - MLP:
              - NOTES: "AI/MODELS/MLP/notes.md"
              - CODE: "AI/MODELS/MLP/code.md"
          - CNN:
              - NOTES: "AI/MODELS/CNN/notes.md"
              - CODE: "AI/MODELS/CNN/code.md"
      - QUANT:
          - CONFIGURATION:
              - NOTES: "AI/QUANT/CONFIG/notes.md"
              - CODE: "AI/QUANT/CONFIG/code.md"
          - INT:
              - NOTES: "AI/QUANT/INT/notes.md"
              - CODE: "AI/QUANT/INT/code.md"
          - FP8:
              - NOTES: "AI/QUANT/FP8/notes.md"
              - CODE: "AI/QUANT/FP8/code.md"
      - TRAIN:
          - DATASET:
              - NOTES: "AI/TRAIN/DATASET/notes.md"
              - CODE: "AI/TRAIN/DATASET/code.md"
          - TRAINER:
              - NOTES: "AI/TRAIN/TRAINER/notes.md"
              - CODE: "AI/TRAIN/TRAINER/code.md"
      - EXAMPLES:
          - MLP:
              - NOTES: "AI/EXAMPLES/MLP/notes.md"
              - CODE: "AI/EXAMPLES/MLP/code.md"
          - CNN:
              - NOTES: "AI/EXAMPLES/CNN/notes.md"
              - CODE: "AI/EXAMPLES/CNN/code.md"
          - ATTENTION:
              - NOTES: "AI/EXAMPLES/ATTENTION/notes.md"
              - CODE: "AI/EXAMPLES/ATTENTION/code.md"


    
# if there are sub nodes under a node, then there should not be a link right after the node. All the stuff should be placed under the node.

# example

# [incorrect use]
# - CLOUD: "./CLOUD/cloud.md"
#     - CLOUD-TECH: "./CLOUD/CLOUD-TECH/cloud-tech.md"

# [correct use]
# - CLOUD: 
#     - "./CLOUD/cloud.md"
#     - CLOUD-TECH: "./CLOUD/CLOUD-TECH/cloud-tech.md"